name: pi_gui
description: "A desktop GUI client for Pi RPC."
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  window_manager: ^0.5.2
  path: ^1.9.0
  flutter_markdown_plus: ^1.0.12
  markdown: ^7.3.1
  url_launcher: ^6.3.2
  highlight: ^0.7.0
  file_selector: ^1.1.0
  path_provider: ^2.1.6
  super_clipboard: ^0.9.1
  dynamic_color: 1.8.1
  flutter_svg: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/backend/workspace_rpc.mjs
    - assets/backend/workspace_manager.mjs
    - assets/backend/workspace_browser.mjs
    - assets/backend/gui_tool_diff.mjs
    - assets/backend/gui_image_upload.mjs
    - assets/images/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans/MiSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/MiSans/MiSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/MiSans/MiSans-Demibold.ttf
          weight: 600
        - asset: assets/fonts/MiSans/MiSans-Bold.ttf
          weight: 700
